### ISSUE TITLE
btoaUTF8 doesn't lint in method btoaReplacer

### ISSUE THREAD

**Issue by ChristineBoersen** [anonyco/BestBase64EncoderDecoder#3]
I think you may have a minor bug in the btoaReplacer method

if (point <= 0x007f) return inputString;
The above line doesn't lint since inputString doesn't exist in this closure (should it be returning point?). 
Also, I don't think the condition can ever be hit, since your original replace's search seems to start it's range at x80

**Comment by anonyco** [comment]
Yikes! You are right: this is most definitely a bug and most definitely introduced by me. I have fixed this frighting bug in the code and updated everything accordingly.

Thankfully, there is no need to change the URL to the Dropbox CDN in your code because Dropbox updates the URL automatically. Thus, everyone who is using this library should receive the bug fix promptly if they are using the Dropbox CDN.

Thank you so much for filing this bug. Please let me know if you find anything other bugs.

[This commit](https://github.com/anonyco/BestBase64EncoderDecoder/compare/master@%7B1552963066%7D...master?diff=split) closes this issue.

**Comment by ChristineBoersen** [comment]
Sounds great. You might want to have MDN update their copy of the code change as well.
